### ISSUE TITLE
Chmod 777 Permission Denied

### ISSUE THREAD

**Issue by HeyYoWhatBro** [WMCB-Tech/debdroid-ng#17]
![Screenshot_20210306-070411](https://user-images.githubusercontent.com/69439251/110183603-3104a600-7e4a-11eb-8193-e5c58b839277.png)
That glitch or just by the system?

How To Fix It?

**Comment by HeyYoWhatBro** [comment]
Also I add chmod +x but still permission denied

**Comment by HeyYoWhatBro** [comment]
And i do use another Sh still work why is not work?

**Comment by WMCB-Tech** [comment]
Ensure that is placed on the `$HOME` Directory and not in `/sdcard`
