### ISSUE TITLE
Add Multilingual Support

### ISSUE THREAD

**Issue by WMCB-Tech** [WMCB-Tech/debdroid-ng#19]

**Comment by Yisus7u7** [comment]
Es sencillo, solo es ejecutar :

sudo apt install locales

sudo su

dpkg-reconfigure locales

Seleccionar el idioma que uno desee

Luego seleccionar el idioma por defecto

luego poner en el .bashrc

export LANG=es_CO

Reemplazar CO por las iniciales de idioma que elejiste

Luego reiniciar termux, y al lanzar debdroid, estará en español, o el idioma que hallas elejido

**Comment by WMCB-Tech** [comment]
the current Implementation is asking a user for language selection during the initial setup just like debian's ncurses setup wizard, if the language is not chosen, then it will fallback to defaults which is english

**Comment by Yisus7u7** [comment]
A si, estoy de acuerdo, algo similiar al repositorio de arch linux en termux, que configuraba el idioma durante la instalacion

**Comment by WMCB-Tech** [comment]
Multilingual Support has been Added, 

Debian container can be updated by doing
`debdroid.sh reconfigure`
