### ISSUE TITLE
Cannot install lxde-desktop

### ISSUE THREAD

**Issue by MTSYuki** [WMCB-Tech/debdroid-ng#20]
I launched Debdroid, and typed sudo apt update.

I copied and pasted debianize lxde-desktop command exactly on README. Everything is going fine, until Debian finished downloaded and configured all the packages.

After "I: Doing Pending Configuration" , an unknown error occurs.

Device: LG K10 2017
Model: LG-M250
ROM: Stock
Android Version: 7.0

Here a screenshot
(BTW, I typed this command a second time, as you can see, the packages already installed)

![Screenshot_2021-03-24-21-19-00](https://user-images.githubusercontent.com/38737250/112401468-5cf8a600-8ce9-11eb-8a21-009dba9e74be.png)

**Comment by WMCB-Tech** [comment]
Ok, it will be fixed soon, just tested on my device

**Comment by WMCB-Tech** [comment]
Seems `tigervnc` wasn't added. and was failed during the check

https://github.com/WMCB-Tech/debdroid-ng/blob/cf1f381e4f80568e36d2045c37444cda238c4957/tasks/lxde-desktop#L3

**Comment by MTSYuki** [comment]
Ah, so only one package is causing the error. I thought my phone was weird.

**Comment by WMCB-Tech** [comment]
@MTSYuki Fixed, Can you run `debianize lxde-desktop` again? see if it helps

**Comment by MTSYuki** [comment]
Okay, I'll run the command again.

**Comment by MTSYuki** [comment]
@WMCB-Tech The command worked now!!

Thanks for the help!!
