### ISSUE TITLE
xfce4 bug

### ISSUE THREAD

**Issue by Yisus7u7** [WMCB-Tech/debdroid-ng#23]
Cuando lanzó xfce4 y ejecutó algún proceso pesado o habro 3 ventanas, de la nada se cae la conexión, eso es algo un poco aburridor, por lo tanto volví a instalar debían mediante proot-distro y configurar el usuario manualmente

Pd: en el debían de proot-distro no se cae el vnc como en debdroid, :C

**Comment by WMCB-Tech** [comment]
Debian Sid's TigerVNC in DebDroid does have a noticable lag, which it has deadlock issues, 

Are you using Debian sid or buster?

**Comment by Yisus7u7** [comment]
Estoy usando debian buster, debdroid con xfce4 tiene un pesimo rendimiento por lo tanto volvi a usar debian con proot-distro:
![Screenshot_20210402-181434](https://user-images.githubusercontent.com/64093255/113463768-7be3f000-93ed-11eb-8412-129ee248cb01.png)

El cual no tengo los mismos errores que arrojaba debdroid

**Comment by WMCB-Tech** [comment]
There may things that you may try to increase performance a bit

1. Disable Execution of host's (Termux) programs by doing

```
echo 0 > /var/debdroid/binfmt/corrosive-session
```

2. Comment out bind mounts by editing:
```
/var/debdroid/mountpoints.conf
```

Performance loss occur due to *proot's* using too much syscalls inside the guest

**Comment by Yisus7u7** [comment]
Hmmm ok, gracias

**Comment by WMCB-Tech** [comment]
Closing this issue as the problem is generally proot or your device's performance
