### ISSUE TITLE
Xsane fails

### ISSUE THREAD

**Issue by mwarrens63** [WMCB-Tech/debdroid-ng#30]
dbus[18908]: arguments to dbus_connection_send() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3307.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace

**Comment by suhan-paradkar** [comment]
I don't think this issue belongs here... Maybe upstream??

**Comment by mwarrens63** [comment]
Suhan, you were correct in your assessment.  dbus service must be running!  If you start dbus, the xsane, simple-scan, etc work fine.  In addition, once I resolved some cups permissions issues, I find that I can I can print to my HP Envy 5660.  I must say that I am VERY pleased with debdroid.  It has turned my Samsung S7+ tablet into a Linux workstation.  Thank you for your efforts!!!
